config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get "home/index"
  get "home/about"
  #root 'home#index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :currect_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twitter, :user_id ])
    end

    def currect_user
      @friend = current_user.friends.find_by(id: params[:id ])
      redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <br>
    <%= form.text_field :first_name ,placeholder:"First Name",class: "form-control" %>
  </div>
  <div>
    <%= form.text_field :last_name ,placeholder:"Last Name",class: "form-control" %>
  </div>
  <div>
    <br>
    <%= form.text_field :email ,placeholder:"Email",class: "form-control" %>
  </div>
  <div>
    <br>
    <%= form.text_field :phone ,placeholder:"Phone",class: "form-control" %>
  </div>
  <div>
    <br>
    <%= form.text_field :twitter ,placeholder:"Twitter",class: "form-control" %>
  </div>
  <div>
    <%= form.number_field :user_id ,placeholder:"User id", id: :friend_user_id, value: current_user.id, class: "form-control", type: :hidden %>
  </div>
  <br>
  <div>
    <%= form.submit class: "btn bg-info" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<% if friend.user == current_user %>
  <tr id="<%= dom_id friend %>">
    <td>
      <%= link_to friend.first_name + ' ' + friend.last_name, friend, class: 'text-decoration-none'%>
    </td>
    <td>
      <%= friend.email %>
    </td>
    <td>
      <%= friend.phone %>
    </td>
    <td>
      <%= friend.twitter %>
    </td>
    <td>
      <%= button_to "Delete", friend, method: :delete, class:"btn btn-danger btn-sm"%>
    </td>
  </tr>
<% end %>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>
<h1>Editing friend</h1>
<%= render "form", friend: @friend %>
<div class="d-flex p-2">
  <%= button_to "Delete", @friend, method: :delete, class:"btn btn-danger btn-sm"%> |
  <%= link_to "Back", friends_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <br>
  <% content_for :title, "Friends" %>
  <h1>Friends</h1>
  <table class="table table-bordered">
    <thead class="table-info">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <%= render friend %>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New friend", new_friend_path, class:"btn bg-info" %>
<% else %>
  <h1>Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
<% end %>

app/views/friends/new.html.erb
<br>
<% content_for :title, "New friend" %>
<h1>Add New Friend</h1>
<div>
  <%= render "form", friend: @friend %>
  <br>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>
<br>

app/views/friends/show.html.erb
<div class="jumbotron bg-body-secondary mx-left p-4">
  <div class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %></p>
</div>
<div>
  <%= @friend.email %></p>
<%= @friend.phone %></p>
<%= @friend.twitter %></p>
</div>
<div>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary"%>
  <%= link_to "Back", friends_path, class:"btn btn-dark"%>
  <br>
  <br>
  <%= button_to "Delete", @friend, method: :delete, class:"btn btn-danger"%>
  <br>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-dark " type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us..</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friend App</title>
    <title><%= content_for(:title) || "Friends App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <%= render "home/header"%>
    <div class="container">
      <% if notice %>
        <br>
        <%= render "layouts/alerts"%>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>